### ISSUE TITLE
feat : Some Logic improvement in js and update UI for better user Experience

### ISSUE THREAD

**Issue by love-sonkar** [Raih1107/To-Do-list-#5]
I wanted to add some logic like when you click in add button the inner text changes to save , if user complete any todo the edit button should be hide only delete button visible because the todo is completed so we don't have to edit the todo and If the user clicks on the edit button and wants to save the empty value then it should not be saved because it cannot be made empty by updating the todo.

**Comment by Raih1107** [comment]
Thanks a lot man for contributing to my project 😃
